<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class CartonDetailSeeder extends Seeder
{
    private $table = 'tblcartondetail';

    public function run()
    {
        $data = [
            [
                'id' => 1,
                'packinglist_carton_id' => 1,
                'product_id' => 1,
                'product_qty' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 2,
                'packinglist_carton_id' => 2,
                'product_id' => 2,
                'product_qty' => 20,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 3,
                'packinglist_carton_id' => 3,
                'product_id' => 2,
                'product_qty' => 16,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 4,
                'packinglist_carton_id' => 4,
                'product_id' => 3,
                'product_qty' => 20,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 5,
                'packinglist_carton_id' => 5,
                'product_id' => 3,
                'product_qty' => 9,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 6,
                'packinglist_carton_id' => 6,
                'product_id' => 4,
                'product_qty' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 7,
                'packinglist_carton_id' => 6,
                'product_id' => 5,
                'product_qty' => 3,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 8,
                'packinglist_carton_id' => 6,
                'product_id' => 6,
                'product_qty' => 5,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 9,
                'packinglist_carton_id' => 6,
                'product_id' => 7,
                'product_qty' => 5,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 10,
                'packinglist_carton_id' => 6,
                'product_id' => 8,
                'product_qty' => 4,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 11,
                'packinglist_carton_id' => 7,
                'product_id' => 9,
                'product_qty' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 12,
                'packinglist_carton_id' => 7,
                'product_id' => 10,
                'product_qty' => 3,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 13,
                'packinglist_carton_id' => 7,
                'product_id' => 11,
                'product_qty' => 5,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 14,
                'packinglist_carton_id' => 7,
                'product_id' => 12,
                'product_qty' => 5,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 15,
                'packinglist_carton_id' => 7,
                'product_id' => 13,
                'product_qty' => 4,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 16,
                'packinglist_carton_id' => 8,
                'product_id' => 4,
                'product_qty' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 17,
                'packinglist_carton_id' => 8,
                'product_id' => 5,
                'product_qty' => 2,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 18,
                'packinglist_carton_id' => 8,
                'product_id' => 6,
                'product_qty' => 4,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 19,
                'packinglist_carton_id' => 8,
                'product_id' => 7,
                'product_qty' => 4,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 20,
                'packinglist_carton_id' => 8,
                'product_id' => 8,
                'product_qty' => 3,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 21,
                'packinglist_carton_id' => 9,
                'product_id' => 9,
                'product_qty' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 22,
                'packinglist_carton_id' => 9,
                'product_id' => 10,
                'product_qty' => 2,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 23,
                'packinglist_carton_id' => 9,
                'product_id' => 11,
                'product_qty' => 4,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 24,
                'packinglist_carton_id' => 9,
                'product_id' => 12,
                'product_qty' => 4,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 25,
                'packinglist_carton_id' => 9,
                'product_id' => 13,
                'product_qty' => 3,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ];
        $this->db->table($this->table)->insertBatch($data);
    }
}
