<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class ProductSeeder extends Seeder
{

    private $table = 'tblproduct';

    public function run()
    {
        $data = [
            [
                'id' => 1,
                'product_code' => '195111263922',
                'product_asin_id' => 'B08J66XGYV',
                'product_category_id' => 5,
                'product_style_id' => 1,
                'product_colour_id' => 1,
                'product_size_id' => 1,
                'product_name' => 'Fleece Pullover Hoodie Sweatshirts',
                'product_price' => 10.8,
                'created_at' => '2023-04-29 10:46:01',
                'updated_at' => '2023-04-29 10:46:01',
            ],
            [
                'id' => 2,
                'product_code' => '195111263939',
                'product_asin_id' => 'B08J5GGYGK',
                'product_category_id' => 5,
                'product_style_id' => 1,
                'product_colour_id' => 1,
                'product_size_id' => 2,
                'product_name' => 'Fleece Pullover Hoodie Sweatshirts',
                'product_price' => 10.8,
                'created_at' => '2023-04-29 10:46:01',
                'updated_at' => '2023-04-29 10:46:01',
            ],
            [
                'id' => 3,
                'product_code' => '195111263946',
                'product_asin_id' => 'B08J6C297M',
                'product_category_id' => 5,
                'product_style_id' => 1,
                'product_colour_id' => 1,
                'product_size_id' => 3,
                'product_name' => 'Fleece Pullover Hoodie Sweatshirts',
                'product_price' => 10.8,
                'created_at' => '2023-04-29 10:46:01',
                'updated_at' => '2023-04-29 10:46:01',
            ],
            [
                'id' => 4,
                'product_code' => '94416036',
                'product_asin_id' => '',
                'product_category_id' => 2,
                'product_style_id' => 2,
                'product_colour_id' => 4,
                'product_size_id' => 1,
                'product_name' => 'AERO GIRLS POLOS - OLIVE (180) - XS',
                'product_price' => 5,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 5,
                'product_code' => '94416044',
                'product_asin_id' => '',
                'product_category_id' => 2,
                'product_style_id' => 2,
                'product_colour_id' => 4,
                'product_size_id' => 2,
                'product_name' => 'AERO GIRLS POLOS - OLIVE (180) - S',
                'product_price' => 5,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 6,
                'product_code' => '94416052',
                'product_asin_id' => '',
                'product_category_id' => 2,
                'product_style_id' => 2,
                'product_colour_id' => 4,
                'product_size_id' => 3,
                'product_name' => 'AERO GIRLS POLOS - OLIVE (180) - M',
                'product_price' => 5,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 7,
                'product_code' => '94416079',
                'product_asin_id' => '',
                'product_category_id' => 2,
                'product_style_id' => 2,
                'product_colour_id' => 4,
                'product_size_id' => 4,
                'product_name' => 'AERO GIRLS POLOS - OLIVE (180) - L',
                'product_price' => 5,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 8,
                'product_code' => '94416087',
                'product_asin_id' => '',
                'product_category_id' => 2,
                'product_style_id' => 2,
                'product_colour_id' => 4,
                'product_size_id' => 5,
                'product_name' => 'AERO GIRLS POLOS - OLIVE (180) - XL',
                'product_price' => 5,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 9,
                'product_code' => '91660645',
                'product_asin_id' => '',
                'product_category_id' => 2,
                'product_style_id' => 2,
                'product_colour_id' => 5,
                'product_size_id' => 1,
                'product_name' => 'AERO GIRLS POLOS - MAGENTA (585) - XS',
                'product_price' => 6,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 10,
                'product_code' => '91660653',
                'product_asin_id' => '',
                'product_category_id' => 2,
                'product_style_id' => 2,
                'product_colour_id' => 5,
                'product_size_id' => 2,
                'product_name' => 'AERO GIRLS POLOS - MAGENTA (585) - S',
                'product_price' => 6,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 11,
                'product_code' => '91660661',
                'product_asin_id' => '',
                'product_category_id' => 2,
                'product_style_id' => 2,
                'product_colour_id' => 5,
                'product_size_id' => 3,
                'product_name' => 'AERO GIRLS POLOS - MAGENTA (585) - M',
                'product_price' => 6,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 12,
                'product_code' => '91660688',
                'product_asin_id' => '',
                'product_category_id' => 2,
                'product_style_id' => 2,
                'product_colour_id' => 5,
                'product_size_id' => 4,
                'product_name' => 'AERO GIRLS POLOS - MAGENTA (585) - L',
                'product_price' => 6,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 13,
                'product_code' => '91660696',
                'product_asin_id' => '',
                'product_category_id' => 2,
                'product_style_id' => 2,
                'product_colour_id' => 5,
                'product_size_id' => 5,
                'product_name' => 'AERO GIRLS POLOS - MAGENTA (585) - XL',
                'product_price' => 6,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ];
        $this->db->table($this->table)->insertBatch($data);
    }
}
